### ISSUE TITLE
[Request]: Deploy service without Pipeline

### ISSUE THREAD

**Issue by zbintliff** [aws/aws-proton-public-roadmap#34]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Deploy a service template (and service) with no pipeline definition.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Working my way through different tutorials trying to replicate a complicated example. My base case is just using the service templates to deploy an ALB and see how powerful the specs and schema can go without having to worry about container definitions. I don't expect any pipeline other than the `infrastructure/cloudformation.yaml` to be created when I deploy a service.  (similar to how environments are handled)

**Are you currently working around this issue?**
 I will look into a noop pipeline but the documentation there is very thin.

**Comment by zbintliff** [comment]
Now that I think about it. Maybe the better request would be a "default" pipeline that follows the same steps as creating an environment?

If I'm misunderstanding something please let me know.

**Comment by zbintliff** [comment]
I think this is required so I created an "empty" CFN template (same thing I did for importing an environment)
```
AWSTemplateFormatVersion: '2010-09-09'
Description:  Empty Pipeline that is required
Conditions:
  AlwaysFalse: !Equals
    - true
    - false
Resources:
  EmptyResource:
    Type: "Custom:EmptyResource"
    Condition: AlwaysFalse
```
