### ISSUE TITLE
[Request]: 

### ISSUE THREAD

**Issue by augentry** [aws/aws-proton-public-roadmap#59]
In an AWS Proton template, we define a variable using Jinja's double curly brace syntax "{{}}". Cloudformation seems to use the same syntax for [dynamic references](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html).

For example using Cloudformation to define a RDS instance with a password stored in Secrets Manager would look like:
```
MyDBInstance2:
    Type: AWS::RDS::DBInstance
    Properties:
    AllocatedStorage: 20
    DBInstanceClass: db.t2.micro
    DBName: !Ref RDSDBName
    Engine: mysql
    MasterUsername:
      Fn::Join:
        - ""
        - - "{{resolve:secretsmanager:"
          - Ref: DBCredentialsSecret
          - ":SecretString:username::}}"
    MasterUserPassword:
      Fn::Join:
        - ""
        - - "{{resolve:secretsmanager:"
          - Ref: DBCredentialsSecret
          - ":SecretString:password::}}"
    MultiAZ: False
    PubliclyAccessible: False      
    StorageType: gp2
    DBSubnetGroupName: !Ref myDBSubnetGroup
    VPCSecurityGroups:
    - !Ref RDSSecurityGroup
    BackupRetentionPeriod: 0
    DBInstanceIdentifier: 'rotation-instance'
```

Is it possible to include a dynamic reference in a Proton template? How can I tell what is going wrong with my template?
