### ISSUE TITLE
[BUG] - Repository Sync Never Creates Service Instances

### ISSUE THREAD

**Issue by lopezm1** [aws/aws-proton-public-roadmap#80]
Hello, 

Me and a few teammates have been running into issues where AWS Proton won't start the repository sync to start create the initial infrastructure deployment. We are trying to create service instances using Terraform templates.

We closely followed the guide here: https://aws.amazon.com/blogs/containers/announcing-git-based-service-deployments-with-service-sync-for-aws-proton/

No matter what we did, we could not get past the initial repository sync to `proton-ops.yaml`. We tried reconfiguring it a few times, but the repository sync never got past:
```
Repository sync status message
Starting syncs for commit 4086defe608f55....
```

------ 
proton-ops.yaml
```yml
sync:
  services:
    mlopez-test:
      dev:
        branch: mlopez
        spec: service-sync.yaml
```

service-sync.yaml
```
proton: ServiceSpec
instances:
  - name: dev
    environment: global-dev-tf
    spec:
      port: 80
      desired_count: 1
      task_size: x-small
      subnet_type: public
      loadbalancer_type: application
      image: 'public.ecr.aws/z9d2n7e1/nginx:1.21.0'
      backendurl: 'backend-svc-inst.backend-svc.fargate-env.local:80'
```

1. We are managing a central infrastructure repo and a central templates repo. 
2. Our template repo has environment + service templates that are deployed into the infrastructure repo. 

----- 
Here is what we tried:

1. We configured our repository sync using both options for available. We configured it once by asking AWS proton to provide the proton-ops and service spec file. We tried more by bringing our own proton-ops and service spec files. Both times, we were stuck at the following:

```
Repository sync status message
Starting syncs for commit 4086defe608f55....
```
2. We tried manually deploying the service from the AWS proton console instead of repository sync. Our template was able to instantly launch the service instance into the environment. This worked ok 👍🏼 

Have you ever had these issues with repository sync before? Any tips for getting past this?
